# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: CulDeVu
email: culdevu@gmail.com
description: > # this means to ignore newlines until "baseurl:"
    [sort description and key words to shove in meta tags]
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://culdevu.github.io" # the base hostname & protocol for your site
twitter_username: CulDeVu
github_username:  CulDeVu

permalink: '/blog/:year/:title/'

# Build settings
markdown: kramdown
