
baseURL = "http://culdevu.github.io/"
languageCode = "en-us"
title = "CulDeVu"
theme = "mainroad"

staticDir = "static"

[Author]
	name = "Daniel Taylor"
	bio = "Email: culdevu@gmail.com"

[Params]
    subtitle = "Just another site" # Subtitle of your site
    description = "The personal website of Daniel Taylor" # Description of your site
    opengraph = true
    readmore = false # Show "Read more" button in list if true
    leftsidebar = false # Move sidebar to the left side if true
    authorbox = true
    postSections = ["post"]

[Params.widgets]
	search = true # Enable "Search" widget
	recent_articles = true # Enable "Recent arcticles" widget
	tags = true # Enable "Tags" widget
		tags_counter = false # Enable counter for each tag in "Tags" widget (disabled by default)